# Generated by Django 2.2 on 2020-02-18 11:22

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertarticle',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='tags.Tagged', to='tags.CustomTag', verbose_name='Tags'),
        ),
    ]
